##Passionate Reports Query
##By Harshan Nagulapally
##SID: 01597680
##to Prof Kui Du

use mydb;

## query for data check
select * from customer;

select * from invoice;

select * from item;

select * from manager;

select * from product;

select * from store;


##1 query for list of customers where purchase price is more than 500

SELECT 
    c.firstname, c.lastname, i.totalamount, i.invoicedate
FROM
    customer AS c,
    invoice AS i
WHERE
    c.customer_id = i.customerid
        AND i.totalamount > 500;


##2 query for the list of managers who made sale in the above 500.

SELECT 
    m.firstname, m.lastname, i.totalamount, i.invoicedate
FROM
    manager AS m,
    invoice AS i
WHERE
    m.managerid = i.manager_managerid
        AND i.totalamount > 500;


##3 query for list of all manager with respective sale made

SELECT 
    m.firstname, (SUM(i.totalamount)) AS SaleMade
FROM
    manager AS m,
    invoice AS i
WHERE
    m.managerid = i.manager_managerid
GROUP BY m.managerid
ORDER BY SaleMade DESC;


##4 list of items with product type availiable and thier quantity

SELECT 
    i.itemname, p.productname, i.quantity
FROM
    item AS i
        LEFT JOIN
    product AS p ON i.productid = p.productcode
;


#5 Revenue generated by each product type

SELECT 
    p.productcode, p.productname, SUM(i.totalamount) AS Revenue
FROM
    invoice AS i
        LEFT JOIN
    product AS p ON i.item_product_productcode = p.productcode
GROUP BY p.productcode
ORDER BY REVENUE DESC
;


#6 Revenu generated by each store

SELECT 
    s.storeid, s.storename, SUM(i.totalamount) AS Revenue
FROM
    invoice AS i
        LEFT JOIN
    store AS s ON i.store_storeid = s.storeid
GROUP BY s.storeid
ORDER BY REVENUE DESC
;